2015/CS3430/finalProject/finalProject/finalProject/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'finalProject.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^', include('polls.urls', namespace="polls")),

    url(r'^admin/', include(admin.site.urls)),

    
    url(r'^login/$', 'django.contrib.auth.views.login'),
)

2015/CS3430/finalProject/finalProject/polls/urls.py
from django.conf.urls import url, patterns, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from finalProject import settings
# from polls import settings

from . import views

urlpatterns = [
	# url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^$', views.index, name='index'),
	url(r'^about$', views.about, name='about'),
	url(r'^home$', views.home, name='home'),
	url(r'^contact$', views.contact, name="contact"),
	url(r'^categories$', views.categories, name="categories"),
	url(r'^details$', views.details, name="details"),
	url(r'^details/(?P<itemId>[0-9]+)$', views.details, name="details"),
	url(r'^login$', views.login, name="login"),
	url(r'^checkout$', views.checkout, name="checkout"),
	url(r'^checkout/(?P<itemId>[0-9]+)$', views.checkout, name="checkout"),
	url(r'^checkout(?P<clear>true)$', views.checkout, name="checkout"),
	url(r'^account$', views.account, name='account'),
	url(r'^cart$', views.cart, name='cart'),
	url(r'^cart/(?P<itemId>[0-9]+)$', views.cart, name="cart"),
	url(r'^cart(?P<clear>true)$', views.cart, name="cart"),
	url(r'^index$', views.index, name='index'),

	# url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
	
	# url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name="detail"),
	# url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
	# url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

# urlpatterns = [
#     url(r'^$', views.IndexView.as_view(), name='index'),
#     url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
#     url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
#     url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
# ]




# 	url(r'^$', views.index, name='index'),
# 	url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
# 	url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
# 	url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
# ]

2015/CS3430/finalProject/finalProject/polls/models.py
import datetime

from django.db import models
from django.utils import timezone


# Create your models here.

class Category(models.Model):
	description = models.CharField(max_length=20)

	def __unicode__(self):
		return self.description


class Item(models.Model):
	price = models.IntegerField(default=0)
	description = models.CharField(max_length=20)
	category = models.ForeignKey(Category)
	picture = models.CharField(max_length=50)
	# description = models.CharField(max_length=200)
	# myQ = models.ForeignKey(Question)

	def __unicode__(self):
		return self.description


# class User(models.Model):
# 	price = models.IntegerField(default=0)
# 	description = models.CharField(max_length=20)
# 	category = models.ForeignKey(Category)
# 	picture = models.CharField(max_length=50)
# 	# description = models.CharField(max_length=200)
# 	# myQ = models.ForeignKey(Question)

# 	def __unicode__(self):
# 		return self.description


# class Question(models.Model):
# 	question_text = models.CharField(max_length=200)
# 	pub_date = models.DateTimeField('date published')

# 	def __unicode__(self):
# 		return self.question_text

# 	def was_published_recently(self):
# 		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
# 	was_published_recently.admin_order_field = 'pub_date'
# 	was_published_recently.boolean = True
# 	was_published_recently.short_description = 'Published recently?'


# class Choice(models.Model):
# 	question = models.ForeignKey(Question)
# 	choice_text = models.CharField(max_length=200)
# 	votes = models.IntegerField(default=0)

# 	def __unicode__(self):
# 		return self.choice_text


	

2015/CS3430/finalProject/finalProject/polls/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from itertools import chain

# from .models import Question
from .models import Item, Category


# for debugging
# import pdb; pdb.set_trace()

def index(request):
	title = "Index";
	return render(request, 'home.html');

def cart(request, itemId=0, clear=False):
	title = "Cart";
	if 'purchase' in request.GET:
		item = Item.objects.filter(id=itemId);
		makeCart(request, item[0]);

	if 'clear' in request.GET:
		clearCart(request);

	total = getTotals(request);

	context = {"context": total};
	return render(request, 'cart.html', context);

def home(request):
	title = "Home";
	return render(request, 'home.html');

def account(request):
	title = "Account";
	# username = None
	if request.user.is_authenticated():
		username = request.user.username;
		return render(request, 'account.html');
	return render(request, 'login.html');	

def about(request):
	return render(request, 'about.html');

def contact(request):
	title = "Contact";
	return render(request, 'contact.html');

def categories(request):
	title = "Categories";
	name = "Adam";
	c = Category.objects.all();
	i = Item.objects.all();
	myVars = []
	for x in c:
		myVars.append({"Category": x, "Items": i.filter(category=x)})
	context = {'pageVars': myVars}
	return render(request, 'categories.html', context);

def details(request, itemId=0):
	title = "Details";
	# import pdb; pdb.set_trace()

	if 'purchase' in request.GET:
		item = Item.objects.filter(id=itemId);
		makeCart(request, item[0]);		

	# request.session.clear();
	i = Item.objects.filter(id=itemId);
	context = {'item': i[0]};
	request.session.name = "Adam";

	return render(request, 'details.html', context);

def login(request):
	title = "Login";

	return render(request, 'login.html');

def checkout(request, itemId=0, clear=False):
	title = "Checkout";
	if 'purchase' in request.GET:
		item = Item.objects.filter(id=itemId);
		makeCart(request, item[0]);

	if 'clear' in request.GET:
		clearCart(request);

	total = getTotals(request);

	context = {"context": total};
	return render(request, 'checkout.html', context);

def makeCart(myRequest, item):
	if 'cart' in myRequest.session:
		temp = myRequest.session['cart'];
		temp.append(item);
		myRequest.session['cart'] = temp;
	else:
		# myRequest['cart'][item['Item']] = item;
		# myRequest['cart'][item['count']] = 0;
		temp = [];
		temp.append(item);
		myRequest.session['cart'] = temp;


def clearCart(myRequest):
	if 'cart' in myRequest.session:
		myRequest.session.clear();


def getTotals(myRequest):
	total = 0;
	if 'cart' in myRequest.session:
		for value in myRequest.session['cart']:
			total = total + value.price;
	return total;

# class IndexView(generic.ListView):
# 	template_name = 'polls/index.html'

	# def get_queryset(self):
	# 	"""return some items from a query"""
	# 	return Category.objects.all();

# class DetailView(generic.ListView):
# 	template_name = 'polls/detail.html'


# class IndexView(generic.ListView):
# 	template_name = 'polls/index.html'
# 	context_object_name = 'latest_question_list'

# 	def get_queryset(self):
# 		"""Return the last five published questions."""
# 		return Question.objects.order_by('-pub_date')[:5]

# class DetailView(generic.DetailView):
# 	model = Question
# 	template_name = 'polls/detail.html'

# class ResultsView(generic.DetailView):
# 	model = Question
# 	template_name = 'polls/results.html'

# def vote(request, question_id):
# 	p = get_object_or_404(Question, pk=question_id)
# 	try:
# 		selected_choice = p.choice_set.get(pk=request.POST['choice'])
# 	except (KeyError, Choice.DoesNotExist):
# 		return render(request, 'polls/details.html', {
# 			'question': p,
# 			'error_message': "You didn't select a choice.",
# 		})
# 	else:
# 		selected_choice.votes += 1
# 		selected_choice.save()

# 	return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))
	# return HttpResponse("You're voting on question %s." % question_id);









# def index(request):
# 	latest_question_list = Question.objects.order_by('-pub_date')[:5]
# 	context = {'latest_question_list': latest_question_list};
# 	return render(request, 'polls/index.html', context);

# def detail(request, question_id):
# 	question = get_object_or_404(Question, pk=question_id);
# 	return render(request, 'polls/detail.html', {'question': question});

# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {'question': question})

2015/CS3430/finalProject/finalProject/polls/templates/about.html
{% include "head.html" %}
{% load staticfiles %}
<!-- Titlebar
================================================== -->
<section class="titlebar">
<div class="container">
	<div class="sixteen columns">
		<h2>About Us</h2>
		
		<nav id="breadcrumbs">
			<ul>
				<li><a href="{% url 'polls:home' %}">Home</a></li>
				<li>About Us</li>
			</ul>
		</nav>
	</div>
</div>
</section>


<!-- Content
================================================== -->

<!-- Container -->
<div class="container">

	<div class="sixteen columns">	
		<h3 class="headline">Our History</h3><span class="line margin-bottom-30"></span><div class="clearfix"></div>
	</div>

	<!-- Who We Are? -->
	<div class="eight columns">
		<p>We are a cat shop. We're all about your cat-purchasing needs. Based out of northern
		Kentucky, we find quality breeds and  sell them to people like you.</p>
		<p>Here to the right you can see some of our most commonly sold products.</p>

	</div>

	<!-- Our Skills -->
	<div class="eight columns">

		<div id="skillzz">

			<div class="skill-bar">
				<span class="skill-title">Calico <i>90%</i></span>
				<div class="skill-bar-value" style="width: 90%;"></div>
			</div>
	
			<div class="skill-bar">
				<span class="skill-title">Brown <i>80%</i></span>
				<div class="skill-bar-value" style="width: 80%;"></div>
			</div>


			<div class="skill-bar">
				<span class="skill-title">White <i>70%</i></span>
				<div class="skill-bar-value" style="width: 70%;"></div>
			</div>

		</div>

	</div>

</div>
<!-- Container / End -->

<div class="margin-top-50"></div>

{% include "foot.html" %}

2015/CS3430/finalProject/finalProject/polls/templates/account.html
{% include "head.html" %}

{{ user.username}}






{% include "foot.html" %}

2015/CS3430/finalProject/finalProject/polls/templates/cart.html
{% include "head.html" %}
{% load staticfiles %}
<!-- Titlebar
================================================== -->
<section class="titlebar">
<div class="container">
	<div class="sixteen columns">
		<h2>Shopping Cart</h2>
		
		<nav id="breadcrumbs">
			<ul>
				<li><a href="#">Home</a></li>
				<li>Shopping Cart</li>
			</ul>
		</nav>
	</div>
</div>
</section>

{% if request.session.cart %}
<div class="container cart">

	<div class="sixteen columns">

		<!-- Cart -->
		<table class="cart-table responsive-table">
			<tr>
				<th>Item</th>
				<th>Description</th>
				<th>Price</th>
				<th>Quantity</th>
				<th>Total</th>
				<th></th>
			</tr>
			{% for item in request.session.cart %}
					
			<!-- Item #1 -->
			<tr>
				<td><img src="{% static '' %}{{ item.picture }}.jpg" alt=""/></td>
				<td class="cart-title"><a href="#">{{ item.description }}</a></td>
				<td>${{ item.price }}.00</td>
				<td>
					<form action='#'>
						<div class="qtyminus"></div>
						<input type='text' name="quantity" value='1' class="qty" />
						<div class="qtyplus"></div>
					</form>
				</td>
				<td class="cart-total">${{ item.price }}.00</td>
				<td><a href="#" class="cart-remove"></a></td>
			</tr>
			{% endfor %}

			</table>

			<!-- Apply Coupon Code / Buttons -->
			<table class="cart-table bottom">

				<tr>
				<th>
					<div class="cart-btns">
						{% if request.user.is_authenticated %}
						<a href="{% url 'polls:checkout' %}" class="button color cart-btns proceed">Proceed to Checkout</a>
						{% else %}
						<a href="{% url 'polls:login' %}" class="button color cart-btns proceed">Login to checkout</a>
						{% endif %}
						<a href="{% url 'polls:cart' %}?clear=True" class="button gray cart-btns">Clear Cart</a>
					</div>
				</th>
				</tr>

			</table>
	</div>


	<!-- Cart Totals -->
	<div class="eight columns cart-totals">
		<h3 class="headline">Cart Totals</h3><span class="line"></span><div class="clearfix"></div>

		<table class="cart-table margin-top-5">

			<tr>
				<th>Cart Subtotal</th>
				<td><strong>${{ context }}.00</strong></td>
			</tr>

			<tr>
				<th>Shipping and Handling</th>
				<td>Free Shipping</td>
			</tr>

			<tr>
				<th>Order Total</th>
				<td><strong>${{ context }}.00</strong></td>
			</tr>

		</table>
		<br>
	</div>

</div>
{% else %}
<div class="container" style="text-align:center;">
	<h3>No items in cart</h3>
</div>
{% endif %}

<div class="margin-top-40"></div>

{% include "foot.html" %}

2015/CS3430/finalProject/finalProject/polls/templates/categories.html
{% include "head.html" %}
{% load staticfiles %}

<div class="container">

<!-- Sidebar
================================================== -->
	<div class="four columns">

		<!-- Categories -->
		<div class="widget margin-top-0">
			<h3 class="headline">Cats</h3><span class="line"></span><div class="clearfix"></div>
			<ul id="categories">
				{% for i in pageVars %}

					<li><a href="#">{{ i.Category }}</a>
						<ul>
						{% for j in i.Items %}
						<li><a href="{% url 'polls:details' %}/{{ j.id }}">{{ j }}</a></li>
						{% endfor %}
						</ul>
					</li>

				{% endfor %}
			</ul>
			<div class="clearfix"></div>
		</div>
	</div>


	<!-- Content
	================================================== -->
	<div class="twelve columns">

	</div>

	<!-- Products -->
	<div class="twelve columns products">


		<!-- Product #1 -->
		{% for c in pageVars %}
			{% for item in c.Items %}
				<div class="four shop columns">
					<figure class="product">
						<div class="mediaholder">
							<a href="{% url 'polls:details' %}/{{ item.id }}">
								<img alt="" src="{% static '' %}{{ item.picture}}.jpg"/>
								<div class="cover">
									<img alt="" src="{% static '' %}{{ item.picture}}1.jpg"/>
								</div>
							</a>

							<a href="{% url 'polls:details' %}/{{ item.id }}?purchase=True" class="product-button"><i class="fa fa-shopping-cart"></i> Add to Cart</a>
						</div>

						<a href="{% url 'polls:details' %}/{{ item.id }}">
							<section>
								<span class="product-category">{{ c.Category }}</span>
								<h5>{{ item }}</h5>
								<span class="product-price">${{ item.price }}.00</span>
							</section>
						</a>
					</figure>
				</div>
			{% endfor %}
		{% endfor %}
				
		<div class="clearfix"></div>

	</div>

</div>

<div class="margin-top-15"></div>


{% include "foot.html" %}

2015/CS3430/finalProject/finalProject/polls/templates/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><string>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
	{% csrf_token %}
	{% for choice in question.choice_set.all %}
		<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
		<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
	{% endfor %}
	<input type="submit" value="Vote" />
</form>
<!-- 
<ul>
{% for choice in question.choice_set.all %}
	<li>{{ choice.choice_text }}</li>
{% endfor %}
</ul> -->

2015/CS3430/finalProject/finalProject/polls/templates/details.html
{% include "head.html" %}
{% load staticfiles %}

<!-- Titlebar
================================================== -->

<div class="container">

<!-- Slider
================================================== -->
	<div class="eight columns" >
		<div class="slider-padding">
			<div id="product-slider-vertical" class="royalSlider rsDefault">
			    <a href="images/product_item_04a-big.jpg" class="mfp-gallery" title="First Title"><img class="rsImg" src="{% static '' %}{{ item.picture }}.jpg" data-rsTmb="{% static '' %}{{ item.picture }}.jpg" alt="" /></a>
			 </div>
			 <div class="clearfix"></div>
		</div>
	</div>


<!-- Content
================================================== -->
	<div class="eight columns">
		<div class="product-page">
			<!-- <h3>{{ request.session.cart }}</h3> -->
			<!-- Headline -->
			<section class="title">
				<h2>{{ item }}</h2>
				<span class="product-price">${{ item.price }}.00</span>
			</section>

			<!-- Text Parapgraph -->
			<section>
				<p class="margin-reset">{{ item.description }}</p>
								
			</section>


			<section class="linking">

					<form action='#'>
						<div class="qtyminus"></div>
						<input type='text' name="quantity" value='1' class="qty" />
						<div class="qtyplus"></div>
					</form>

					<a href="{% url 'polls:cart' %}/{{ item.id }}?purchase=True" class="button adc">Add to Cart</a>
					<div class="clearfix"></div>

			</section>

		</div>
	</div>

</div>

<div class="margin-top-50"></div>

{% include "foot.html" %}

2015/CS3430/finalProject/finalProject/polls/templates/head.html
<!DOCTYPE html>
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

<!-- Basic Page Needs
================================================== -->
<meta charset="utf-8">
<title>Cats</title>

<!-- Mobile Specific Metas
================================================== -->
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

<!-- CSS
================================================== -->

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}">
<link rel="stylesheet" href="{% static 'polls/css/colors/green.css' %}" id="colors">

 
<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

</head>

<body class="boxed">
<div id="wrapper">


<!-- Top Bar
================================================== -->
<div id="top-bar">
	<div class="container">

		<!-- Top Bar Menu -->
		<div class="ten columns">
			<ul class="top-bar-menu">
				<li><i class="fa fa-phone"></i> (800) 123-4567</li>
				<li><i class="fa fa-envelope"></i> <a href="#">support@cats.com</a></li>
			</ul>
		</div>

		{% if request.user.is_authenticated %}
		<div class="six columns">
			<ul class="top-bar-menu">
				<li>Logged in as {{ user.username }}</li>
			</ul>
		</div>
		{% endif %}

	</div>
</div>

<div class="clearfix"></div>


<!-- Header
================================================== -->
<div class="container">

	<!-- Logo -->
	<div class="four columns">
			<div id="logo">
				<h1><!-- <a href="{% url 'polls:about' %}"><img src="{% static 'polls/images/logo.png' %}" alt="Trizzy" /></a> -->&nbsp;</h1>
			</div>
	</div>
	

	<!-- Additional Menu -->
	<div class="twelve columns">
		<div id="additional-menu">
			<ul>
<!-- 				<li><a href="{% url 'polls:cart' %}">Shopping Cart</a></li>
				<li><a href="{% url 'polls:account' %}">My Account</a></li> -->
			</ul>
		</div>
	</div>

	
	<!-- Shopping Cart -->
	<div class="twelve columns">

		<div id="cart">
				
			<!-- Button -->
			<div class="cart-btn">
				<a href="#" class="button adc">&nbsp;</a>
			</div>

			<div class="cart-list">

			<div class="arrow"></div>

				{% if request.session.cart %}
				<div class="cart-amount">
					<span>items in the shopping cart</span>
				</div>

					<ul>
					{% for item in request.session.cart %}
						<li>
							<a href="#"><img src="{% static '' %}{{ item.picture }}.jpg" alt="" /></a>
							<a href="#">{{ item.description }} <br /> Cat</a>
							<span>${{ item.price }}.00</span>
							<div class="clearfix"></div>
						</li>
						{% endfor %}
					</ul>

				<div class="cart-buttons button">
					<a href="{% url 'polls:cart' %}" class="view-cart" ><span data-hover="View Cart"><span>View Cart</span></span></a>
					<a href="{% url 'polls:checkout' %}" class="checkout"><span data-hover="Checkout">Checkout</span></a>
				</div>
				<div class="clearfix"></div>
				{% else %}
				<div class="cart-amount">
					<span>No items in the shopping cart</span>
				</div>
				{% endif %}
			</div>

		</div>

		<!-- Search -->
		<nav class="top-search">
			<form action="#" method="get">
				<button><i class="fa fa-search"></i></button>
				<input class="search-field" type="text" placeholder="Search" value=""/>
			</form>
		</nav>

	</div>

</div>


<!-- Navigation
================================================== -->
<div class="container">
	<div class="sixteen columns">

		<a href="#menu" class="menu-trigger"><i class="fa fa-bars"></i> Menu</a>

		<nav id="navigation">
			<ul class="menu" id="responsive">
				<li><a href="{% url 'polls:home' %}"><i class="fa fa-home"></i></a></li>
				<li><a href="{% url 'polls:about' %}">about</a></li>
				<li><a href="{% url 'polls:contact' %}">contact</a></li>
				<li><a href="{% url 'polls:categories' %}">categories</a></li>
				<!-- <li><a href="{% url 'polls:details' %}/3">detail</a></li> -->
				<li><a href="{% url 'polls:checkout' %}">checkout</a></li>
				<li><a href="{% url 'polls:cart' %}">cart</a></li>
				<li><a href="{% url 'polls:login' %}">login</a></li>
			</ul>
		</nav>							
	</div>
</div>

2015/CS3430/finalProject/finalProject/polls/templates/home.html
{% include "head.html" %}
{% load staticfiles %}
<!-- Slider
================================================== -->
<div class="container fullwidth-element home-slider">

	<div class="tp-banner-container">
		<div class="tp-banner">
			<ul>
				<!-- Slide 1  -->
				<li data-transition="fade" data-slotamount="7" data-masterspeed="1500" >
					<img src="{% static 'polls/images/cats/slider1.jpg' %}"  alt="slidebg1"  data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat">
 					<div class="caption sfb fadeout" data-x="145" data-y="170" data-speed="400" data-start="800"  data-easing="Power4.easeOut">
						<h2></h2>
						<h3></h3>
						<!-- <a href="shop-with-sidebar.html" class="caption-btn">Shop The Collection</a> -->
					</div>
				</li>

				<!-- Slide 2  -->
				<li data-transition="zoomout" data-slotamount="7" data-masterspeed="1000">
 					<img src="{% static 'polls/images/cats/slider2.jpg' %}"  alt="darkblurbg"  data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat">
 					<div class="caption dark sfb fadeout" data-x="750" data-y="170" data-speed="400" data-start="800"  data-easing="Power4.easeOut">
						<h2></h2>
						<h3></h3>
						<!-- <a href="shop-with-sidebar.html" class="caption-btn">Shop The Collection</a> -->
					</div>
				</li>

				<!-- Slide 3  -->
				<li data-transition="fadetotopfadefrombottom" data-slotamount="7" data-masterspeed="1000">
 					<img src="{% static 'polls/images/cats/slider3.jpg' %}"  alt="darkblurbg"  data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat">
 					<div class="caption dark sfb fadeout" data-x="850" data-y="170" data-speed="400" data-start="800"  data-easing="Power4.easeOut">
						<h2></h2>
						<h3></h3>
						<!-- <a href="shop-with-sidebar.html" class="caption-btn">Shop The Collection</a> -->
					</div>
				</li>

			</ul>
		</div>
	</div>
</div>


<!-- Featured
================================================== -->
<div class="container" >

	<div class="one-third column">
		<a href="{% url 'polls:details' %}/5" class="img-caption" >
			<figure>
				<img src="{% static 'polls/images/cats/brown1.jpg' %}" alt="" />
				<figcaption>
					<h3>Black Cats</h3>
					<span></span>
				</figcaption>
			</figure>
		</a>
	</div>

	<div class="one-third column">
		<a href="{% url 'polls:details' %}/4" class="img-caption" >
			<figure>
				<img src="{% static 'polls/images/cats/white1.jpg' %}" alt="" />
				<figcaption>
					<h3>White Cats</h3>
					<span></span>
				</figcaption>
			</figure>
		</a>
	</div>

	<div class="one-third column">
		<a href="{% url 'polls:details' %}/7" class="img-caption" >
			<figure>
				<img src="{% static 'polls/images/cats/spotted1.jpg' %}" alt="" />
				<figcaption>
					<h3>Spotted Cats</h3>
					<span></span>
				</figcaption>
			</figure>
		</a>
	</div>

</div>
<div class="clearfix"></div>


<div class="margin-top-50"></div>

{% include "foot.html" %}

2015/CS3430/finalProject/finalProject/polls/templates/login.html
{% include "head.html" %}


<!-- Titlebar
================================================== -->
<section class="titlebar">
<div class="container">
	<div class="sixteen columns">
		<h2>My Account</h2>
		
		<nav id="breadcrumbs">
			<ul>
				<li><a href="#">Home</a></li>
				<li>My Account</li>
			</ul>
		</nav>
	</div>
</div>
</section>


<!-- Content
================================================== -->

<!-- Container -->
<div class="container">

	<div class="six columns centered">

		<div class="tabs-container">
			<!-- Login -->
			<div class="tab-content" id="tab1">

				<h3 class="headline">Login</h3><span class="line" style="margin-bottom:20px;"></span><div class="clearfix"></div>

				<form method="post" action="{% url 'polls:home' %}">{% csrf_token %}
					
					
						<table>
							<tr>
								<td>{{ form.username.label_tag }}</td>
								<td>{{ form.username }}</td>
							</tr>
							<tr>
								<td>{{ form.password.label_tag }}</td>
								<td>{{ form.password }}</td>
							</tr>
						</table>

					<p class="form-row form-row-wide">
						<label for="username">Username or Email Address: <span class="required">*</span></label>
						<input type="text" class="input-text" name="username" id="username" value="{{ username.username }}" autofocus/>
					</p>

					<p class="form-row form-row-wide">
						<label for="password">Password: <span class="required">*</span></label>
						<input class="input-text" type="password" name="password" id="password" />
					</p>

					<p class="form-row">
						<input type="submit" class="button" name="login" value="Login" />
						<input type="hidden" name="next" value="{{ next }}">
					</p>

					
				</form>
			</div>
		</div>
	</div>
</div>

<div class="margin-top-50"></div>


{% include "foot.html" %}